# Generated by Django 5.1.5 on 2025-02-03 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 21, 9, 17, 202564)),
        ),
    ]
