# Generated by Django 5.1.7 on 2025-03-11 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 13, 31, 42, 177437)),
        ),
    ]
